[package]
name = "aura-codegen"
version = "0.1.0"
edition = "2024"

[features]
default = []
llvm-backend = ["dep:inkwell"]

[dependencies]
aura-diagnostics = { path = "../aura-diagnostics" }
aura-frontend = { path = "../aura-frontend" }
aura-runtime-host = { path = "../aura-runtime-host" }
aura-typecheck = { path = "../aura-typecheck" }
inkwell = { version = "0.5", default-features = false, features = ["llvm18-0-prefer-dynamic"], optional = true }
